### ISSUE TITLE
Incorporate into flatten-tweet NPM package?

### ISSUE THREAD

**Issue by edsu** [jamauro/flatten-twitterv2#1]
This is a super elegant piece of code! I much prefer it to what I cooked up over in [docnow/flatten-twitter](https://twitter.com/docnow/flatten-twitter) to solve the exact same problem. I was wondering if you would be ok with me merging it and sending it up to NPM? I can give you edit permissions on the docnow/flatten-twitter repository.

**Comment by jamauro** [comment]
Thanks! Sorry for the delayed reply. If I understand you correctly, feel free to copy the code and use it in your project if you'd like. I'm planning to keep this as a small function that's agnostic to how the twitter API is called. As an fyi, it sounds like twitter may be making some changes to how the data in `includes` can be retrieved which should simplify my code even more. We'll see.

**Comment by edsu** [comment]
Thanks @jamauro! Do you have a link for that discussion about includes? It would be a welcome change as long as the situation is not made worse...

**Comment by jamauro** [comment]
Yep check this out: https://github.com/twitterdev/open-evolution/blob/main/001-keyed-expansions.md

**Comment by edsu** [comment]
Thanks! That proposal makes a lot of sense.
